#pragma once

enum DIRECTION { LEFT, RIGHT, UP, DOWN, DEATH,END };

enum OBJID { OBJ_PLAYER,OBJ_SPLAYER, OBJ_BULLET,OBJ_BUTTON,OBJ_FLAG,OBJ_CHAR,OBJ_CARROT,OBJ_ONION,OBJ_WALL,OBJ_POTATO,
	OBJ_PBULLET,OBJ_OBULLET,OBJ_CBULLET, OBJ_CARROTBEAM, OBJ_BONBON,
	OBJ_DICEKING,OBJ_DICE,OBJ_CARD,OBJ_BACKGROUND,OBJ_COIN,OBJ_BBULLET,

	OBJ_FLOWER,OBJ_COLLISION,OBJ_ACORN, OBJ_FBULLET, OBJ_CLONG,OBJ_CSHORT,OBJ_SEED, OBJ_VENES,OBJ_EFFECT,
	OBJ_EVENTCOIN,OBJ_EVENTEFFECT,
	OBJ_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_TUTORIAL, SC_STAGE,SC_RETURN01, SC_STAGE01, SC_STAGE02, SC_STAGE03, SC_ENDING,SC_END };

enum RENDERID { RENDER_BACKGROUND, RENDER_BACKCOIN,RENDER_BACKOBJ, RENDER_OBJ, RENDER_UI, RENDER_EFFECT,RENDER_TREE,RENDER_COINEFFECT,RENDER_UI2, RENDER_END };

enum CHANNELID { SOUND_EFFECT, SOUND_MAIN,SOUND_BGM, SOUND_FARM,SOUND_PLAYER,SOUND_ONION,SOUND_FLOWER,SOUND_BULLET, SOUND_MONSTER, SOUND_VICTORY,MAXCHANNEL };
